language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests
deploy:
  provider: pypi
  skip_cleanup: true
  user: Marx314
  password:
    secure: CcUJllcvmHs3i/ma68vOwX9qFUEYzrj8XHMRpZ1AQH19e04udoq6fFc9xEViXEXgdnY5xtNj65lvjWX6HXFT5QnoFwSho8Ug+ZuNAIteE9Wj6WWoKyEVn45lwPfFnMdc8hkhHEDvzAD8IzQ4J0NitmuiRQnuqza2onjlZ2oBTEWxYDm1ObTYNS2RnloUsJwd29Ze5eoFijrVzKr+isbJh3wVG6mIFX318AV3qErMr/6GFetqXTlftWA1vdSptH+7VErVD9Jo7EE0bs2zuCfGkTFZiNTKAFOoWLzQf9zMf+6i9cfcxBkqc4RJz6vEGXgnS2Z7bTLVM6TLDCkxx8fKVlRaYqYF+GKGgfVu2z1546OxC+Tf4vR2yg2Dt2lBBR07VAYyLCO5gPNTfFvl9ZEEaukXqdpxqq+b2da+BkMdkENba7MsoVGl9oozXFTdaIX4Ov8K++pWUFQQw/pXbrnlrUrbbAHlWVlYsmuLoxJiQSJCSEVb/AgZPHEKH8of7QSJYM+F2caGcb6Tkz81jrcEhGf8CSPqpEeax0fQ04V5aXfb4k2AFkZCLtpDuGw+JiVeU6EUXOOuM1aubrTqYT22sAaWftu/tbFVRQoQtZu55Qp4pCANPwNpj2QofhWWJebifdE9C3dDPvNcZ1u4+aZUnijd9nSZkFpsxyh38qtp+qE=
  on:
    tags: true
    python: 3.4
    repo: Marx314/python-ubersmithclient
