language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests
deploy:
  provider: pypi
  skip_cleanup: true
  user: internaphosting
  password:
    secure: EhNo/cPaxkOXMU0gaUbRCKl5Rx7SZrhbbwFv5Er3xmMnBNGjRQq/gZ2O1OVhJdiy5VixPugCguqj+/6iAWk2k7G0c4QcluAG/NOK+XpX+ETQ5koN1cVNWJJObgWcbxq3LCAKzRWiRV1yNhhBYj2foTHmUbU8LLsW7ALALBoCrfrOFpG/Gds+XcyGv4VNrnIUAiFsTJ2F83Vug3JtBlddbIR/tMMrgf64cy+Ps9sJeknMFT49+NwYuZWFb+haZdGRTNEXw4wcZNhadHIjlnN57/8uZy/14AEw2CkOMtMIu8BdOrzu/18V6og6VRsI91Z5QbdPytnhxr2BRi+hAUNUdk5KG6HHBPiIfCVLqKtZBDkZREuC3DpnEld0H7ZriWw+Pk8f3rFmKeqwaLqVHkoo4ItF97M1d1zyirMSDAY7ashyonrRemosUVfv9MXmrxCc6VLitOMngdWwa5TtArkEwt8q/675IQishL908u8EB1/q0cooZWt6QQXggulf28fqNHnQdDb/4stSIOsWchVVvNNqJZUArToY6wOU5ka6nMyDP4amr60D+hLwjxOTq6NiXmbR5DvkO7Z/3XYevO6TVoiCG+We+zNN2cCbZQqtgJ++8xATPM0aF913zsZ2iG3CzBo18cr5zH0AGJjo+t88aF69DVbYnvo20RgqpsSEH0E=
  on:
    tags: true
    python: 3.4
    repo: internap/python-ubersmithclient
